# -*- coding: utf-8 -*-
"""froud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuT22SXWmKZEMF2ZUF2eekufuK3RrkU5
"""

import pandas as pd
import numpy as np
import streamlit as st
import pickle

# Load model
model = pickle.load(open("fraud_detection_model.pkl", "rb"))
   
st.set_page_config(page_title="Fraud Detection System", page_icon="💳")

st.title("💳 Credit Card Fraud Detection System")
st.write("Enter transaction details to detect whether transaction is Fraud or Genuine.")

st.sidebar.header("Transaction Input Features")

# Input fields
Time = st.sidebar.number_input("Time", value=0.0)
Amount = st.sidebar.number_input("Amount", value=100.0)

features = {}

for i in range(1, 29):
    features[f"V{i}"] = st.sidebar.number_input(f"V{i}", value=0.0)

# Create dataframe in correct order
input_data = pd.DataFrame({
    "Time": [Time],
    "V1": [features["V1"]],
    "V2": [features["V2"]],
    "V3": [features["V3"]],
    "V4": [features["V4"]],
    "V5": [features["V5"]],
    "V6": [features["V6"]],
    "V7": [features["V7"]],
    "V8": [features["V8"]],
    "V9": [features["V9"]],
    "V10": [features["V10"]],
    "V11": [features["V11"]],
    "V12": [features["V12"]],
    "V13": [features["V13"]],
    "V14": [features["V14"]],
    "V15": [features["V15"]],
    "V16": [features["V16"]],
    "V17": [features["V17"]],
    "V18": [features["V18"]],
    "V19": [features["V19"]],
    "V20": [features["V20"]],
    "V21": [features["V21"]],
    "V22": [features["V22"]],
    "V23": [features["V23"]],
    "V24": [features["V24"]],
    "V25": [features["V25"]],
    "V26": [features["V26"]],
    "V27": [features["V27"]],
    "V28": [features["V28"]],
    "Amount": [Amount]
})

st.subheader("Entered Transaction Data")
st.write(input_data)

if st.button("Predict Transaction"):
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("🚨 Fraud Transaction Detected!")
    else:
        st.success("✅ Genuine Transaction")