# -*- coding: utf-8 -*-
"""froud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuT22SXWmKZEMF2ZUF2eekufuK3RrkU5
"""
import pandas as pd
import streamlit as st
import pickle

model = pickle.load(open("fraud_detection_model.pkl", "rb"))

st.set_page_config(page_title="Fraud Detection System", page_icon="💳")

st.title("💳 Credit Card Fraud Detection System")
st.write("Enter transaction details to detect whether transaction is Fraud or Genuine.")

st.sidebar.header("Transaction Input Features")

Time = st.sidebar.number_input("Time", value=0.0)
Amount = st.sidebar.number_input("Amount", value=100.0)

features = {}
for i in range(1, 29):
    features[f"V{i}"] = st.sidebar.number_input(f"V{i}", value=0.0)

input_data = pd.DataFrame({
    "Time": [Time],
    **{f"V{i}": [features[f"V{i}"]] for i in range(1, 29)},
    "Amount": [Amount]
})

# Important fix
if hasattr(model, "feature_names_in_"):
    required_cols = list(model.feature_names_in_)
    input_data = input_data.reindex(columns=required_cols, fill_value=0)

st.subheader("Entered Transaction Data")
st.write(input_data)

if st.button("Predict Transaction"):
    prediction = model.predict(input_data)[0]

    if prediction == 1:
        st.error("🚨 Fraud Transaction Detected!")
    else:
        st.success("✅ Genuine Transaction")
